def init() -> None: ...


class Shader:
    # OpenGL object ID
    glo: int

    def __init__(
        self,
        fragment_source: str,
        vertex_source: str,
        geometry_source: str="",
    ) -> None: ...

    def bind(self) -> None: ...
    def unbind(self) -> None: ...
    def __hash__(self) -> None: ...
    def __del__(self) -> None: ...
    def __str__(self) -> None: ...
