import numpy as np


def init() -> None: ...


class VertexBuffer:
    def __init__(self, array: np.ndarray) -> None: ...
    def __str__(self) -> None: ...
    def bind(self) -> None: ...
    def unbind(self) -> None: ...
    def __del__(self) -> None: ...
